#!/usr/bin/env python3
"""Generate TypeScript Uint8Array from Wireshark hex dump files."""

import re
import sys
from pathlib import Path


def parse_hex_dump(text: str) -> bytes:
    out = bytearray()
    for line in text.strip().splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        parts = line.split()
        hex_part = []
        for p in parts[1:]:
            if len(p) == 2 and all(c in "0123456789abcdefABCDEF" for c in p):
                hex_part.append(p)
            else:
                break
        if hex_part:
            out.extend(bytes.fromhex("".join(hex_part)))
    return bytes(out)


def to_ts_array(data: bytes, name: str, comment: str) -> str:
    lines = [f"/** {comment} */", f"export const {name} = new Uint8Array(["]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) >= 16:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("]);")
    lines.append(f"export const {name}_SIZE = {len(data)};")
    return "\n".join(lines)


def main() -> None:
    tools = Path(__file__).parent
    for cap in ("capture1", "capture2", "capture3"):
        path = tools / f"{cap}.hex"
        if not path.exists():
            print(f"skip missing {path.name}")
            continue
        data = parse_hex_dump(path.read_text(encoding="utf-8"))
        print(f"{cap}: {len(data)} bytes (0x{len(data):X})")

    cap3 = tools / "capture3.hex"
    if not cap3.exists():
        sys.exit("capture3.hex missing")
    p1 = parse_hex_dump(cap3.read_text(encoding="utf-8"))
    out = tools.parent / "src" / "helper" / "labviewSaveCapture3.ts"
    header = to_ts_array(
        p1,
        "LABVIEW_SAVE_CAPTURE3_P1",
        "Wireshark CAP3 — Addr1 Ch236 P500 (full 0x101B replay)",
    )
    out.write_text(
        "/** Auto-generated by tools/generate-save-capture-ts.py — do not edit by hand. */\n\n"
        + header
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
